-- Convert primary and foreign keys from BIGINT to VARCHAR(36)
ALTER TABLE users ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;

ALTER TABLE categories ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;

ALTER TABLE auctions ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE auctions ALTER COLUMN seller_id TYPE VARCHAR(36) USING seller_id::VARCHAR;
ALTER TABLE auctions ALTER COLUMN category_id TYPE VARCHAR(36) USING category_id::VARCHAR;
ALTER TABLE auctions ALTER COLUMN current_winner_id TYPE VARCHAR(36) USING current_winner_id::VARCHAR;

ALTER TABLE bids ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE bids ALTER COLUMN auction_id TYPE VARCHAR(36) USING auction_id::VARCHAR;
ALTER TABLE bids ALTER COLUMN bidder_id TYPE VARCHAR(36) USING bidder_id::VARCHAR;

ALTER TABLE bid_history_entries ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE bid_history_entries ALTER COLUMN auction_id TYPE VARCHAR(36) USING auction_id::VARCHAR;

ALTER TABLE payments ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE payments ALTER COLUMN auction_id TYPE VARCHAR(36) USING auction_id::VARCHAR;

ALTER TABLE auto_bid_configs ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE auto_bid_configs ALTER COLUMN auction_id TYPE VARCHAR(36) USING auction_id::VARCHAR;
ALTER TABLE auto_bid_configs ALTER COLUMN bidder_id TYPE VARCHAR(36) USING bidder_id::VARCHAR;

ALTER TABLE audit_logs ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE audit_logs ALTER COLUMN entity_id TYPE VARCHAR(36) USING entity_id::VARCHAR;

ALTER TABLE auction_images ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE auction_images ALTER COLUMN auction_id TYPE VARCHAR(36) USING auction_id::VARCHAR;

ALTER TABLE user_account_logs ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE user_account_logs ALTER COLUMN target_user_id TYPE VARCHAR(36) USING target_user_id::VARCHAR;

ALTER TABLE user_roles ALTER COLUMN user_id TYPE VARCHAR(36) USING user_id::VARCHAR;
ALTER TABLE user_roles ALTER COLUMN role_id TYPE VARCHAR(36) USING role_id::VARCHAR;

ALTER TABLE roles ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;

ALTER TABLE otps ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;
ALTER TABLE otps ALTER COLUMN user_id TYPE VARCHAR(36) USING user_id::VARCHAR;
