ALTER TABLE audit_logs
  DROP CONSTRAINT IF EXISTS audit_logs_action_check;

ALTER TABLE audit_logs
  ADD CONSTRAINT audit_logs_action_check
  CHECK (action IN (
    'LOGIN_SUCCESS',
    'LOGIN_FAILURE',
    'LOGOUT',
    'REGISTER',
    'PASSWORD_CHANGE',
    'PASSWORD_RESET',
    'AUCTION_CREATED',
    'AUCTION_REVIEWED_APPROVED',
    'AUCTION_REVIEWED_REJECTED',
    'BID_PLACED',
    'BID_REJECTED',
    'USER_LOCKED',
    'USER_UNLOCKED',
    'PROFILE_UPDATED',
    'OTP_SENT',
    'OTP_VERIFIED',
    'OTP_FAILED',
    'TOKEN_REFRESHED',
    'TOKEN_BLACKLISTED',
    'AUTO_BID_CONFIGURED',
    'AUTO_BID_DEACTIVATED',
    'PAYMENT_INITIATED',
    'PAYMENT_SUCCEEDED',
    'PAYMENT_FAILED',
    'AUCTION_ACTIVATED',
    'AUCTION_ENDED',
    'CATEGORY_CREATED',
    'CATEGORY_UPDATED',
    'CATEGORY_DELETED',
    'BID_PLACED_WS',
    'CLOUDINARY_UPLOAD_FAILED'
  ));
