package com.example.daugia.common.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    AUCTION_CREATED,
    AUCTION_REVIEWED_APPROVED,
    AUCTION_REVIEWED_REJECTED,
    BID_PLACED,
    BID_REJECTED,
    USER_LOCKED,
    USER_UNLOCKED,
    PROFILE_UPDATED
}